# Taken and modified from
# https://github.com/applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics/blob/master/.travis.yml

dist: bionic
language: python
services:
  - xvfb
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda env create -n workshop-env -f environment.yml
  - source activate workshop-env
script:
  - ipymd --from markdown --to notebook lessons/*.md